### ISSUE TITLE
Develop and Define Server to Dispenser communication

### ISSUE THREAD

**Issue by nhhollander** [ECE2305-Group-25/TPaaS#12]
While we've made good progress towards refining the client to server API, we still haven't settled on a good way to do the next leg of communication, from the server to the dispenser.  I've thought of a few different ways, but they all have their pros and cons.

**Raw TCP Socket:**
| Pros | Cons |
|-|-|
| ✔️ Low latency | ❌ No Security |
| ✔️ Relatively Straightforward | ❌ We'd have to write everything (no boilerplate) |
| ✔️ Low bandwidth | ❌ Incompatible with proxies or load balancers (nginx, cloudflare, etc) |

**HTTP(s) Requests (from dispenser to server):**
| Pros | Cons |
|-|-|
| ✔️ Secure | ❌ High Latency |
| ✔️ Trivial Implementation | ❌ Difficult to detect if dispenser goes offline  |
| ✔️ High compatibility | ❌ High(er) bandwidth |

**WebSockets:**
| Pros | Cons |
|-|-|
| ✔️ Secure | ❌ Requires use of external libraries on both devices |
| ✔️ Low Latency | ❌ Implementation may be more difficult  |
| ✔️ Moderate compatibility | ❌ Not well documented for python |

Based on my personal experience, I think WebSockets might be the best bet here, although I'd like to get some feedback from others on which system you all think would be best.  I have written WebSocket server code in python before, but I've never written a WebSocket client in python.

**Comment by brycecorbitt** [comment]
We don't have a server defined like this in our Design Proposal. See [my comment](https://github.com/ECE2305-Group-25/TPaaS/issues/7#issuecomment-612654356) on #7.
