### ISSUE TITLE
Write Driver Code for Electronic Components

### ISSUE THREAD

**Issue by brycecorbitt** [ECE2305-Group-25/TPaaS#5]
Driver code must be written to interface with the following components:

- IR Proximity Sensor (may be adapted from previous use [here](https://github.com/brycecorbitt/HU3910_PianoHand/blob/master/drivers/proximity_sensor.py))
- Servos (may be adapted from previous use [here](https://github.com/brycecorbitt/HU3910_PianoHand/blob/master/drivers/servo.py))
- Display for PIN based authentication
- Continuity detection between GPIO pins to check if lid is open

**Comment by nhhollander** [comment]
I'll expand the boilerplate server code to include skeleton modules for each of these requirements.

**Comment by brycecorbitt** [comment]
Alright, give me an update when you have it committed/pushed. I already have code to interface with each of them actually, I just need to make it a bit cleaner and put it in the server where you see fit.

**Comment by brycecorbitt** [comment]
Driver modules for each electric component have been added! The image below shows the output to a little demo of a few of the components working together. The display is showing the current voltage reading from the proximity sensor (in volts), as well as the output from the lid switch pin indicating that it has a closed connection (same logic as the lid being closed).

![Component Driver Demo](https://i.imgur.com/0qxC4d4.jpg)
