### ISSUE TITLE
Develop PIN Authentication Module

### ISSUE THREAD

**Issue by brycecorbitt** [ECE2305-Group-25/TPaaS#8]
Build a simple Python3 module to be used in PIN based authentication. Deliverables are as follows:

- PIN takes the form of a 4 digit number
- A field that keeps track of the currently generated pin internally
- Method to generate new PIN
- Method that is passed a number and compares with currently generated PIN

While it does not need to be implemented in this module, functionality to prevent the generation of a new PIN within a specified period of time from generating the current PIN should be considered. Otherwise, a user could possibly rapid-fire pin generation to deny another user reliable access to the dispenser. This functionality may need to be implemented in a higher level module or in the API endpoint itself.

**Comment by nhhollander** [comment]
@brycecorbitt Do you envision the PIN generation pipeline to be something like this?
![](https://i.imgur.com/IMIGJko.png)

**Comment by brycecorbitt** [comment]
Yeah, that looks spot on. It doesn't need to be anything fancy, as long as it can generate a PIN number and authenticate with them it'll do fine. 

At some point down the road, we may want to write something to keep track of how much time has passed since the last time a new PIN number was generated so that we can prevent the server from changing the PIN while a user could be trying to enter the older PIN. This would really only happen if another person requested to dispense on a different device at the same time, but it's something to consider. We can discuss it in more depth at our next meeting.

**Comment by nhhollander** [comment]
Okay I've implemented this with two API calls.

The first endpoint is `/api/generate_pin`, which generates a new PIN and displays it on the screen (currently a stub method).

The second endpoint is `/api/dispense` which I modified to accept the pin generated via the call to `/api/generate_pin`.

Documentation is in [API.md](https://github.com/ECE2305-Group-25/TPaaS/blob/master/server/API.md)

**Comment by nhhollander** [comment]
Should we consider making the pin expire after a fixed period of time?  Or should we just assume that once generated a pin will last until the next one is generated.  If not, we can probably close this issue.

**Comment by brycecorbitt** [comment]
I just thought about this a lot. Originally I was thinking "yeah, that sounds like a good idea", and I still think it's a good idea for security sake. However, I also was thinking about how the display would incorporate into it; you'd probably want to clear the screen once the PIN expires, otherwise you could run into the case of someone entering a pin while it's expired and having the operation fail. Clearing the screen after a fixed time period would likely require multithereading or implementing some asynchronous operation, which would things more complicated than they need to be.

The code you have pushed now looks good to me. At some point we'll need to think about incorporating the display into it, but that's outside the scope of what I had planned for this issue.
